### ISSUE TITLE
[BUG] Request still staying on requests page after full approval

### ISSUE THREAD

**Issue by smblackwll** [uiowaSEP2024/003_MAGNA#169]
**Describe the bug:**

Sometimes, despite a form finished routing and being approved, it still appears on a manager's dashboard. Then, when it's clicked on, an error is thrown, since the form returns a NoneType.

**To Reproduce:**

1. Go to #71 Branch
2. Fill out a form as a kiosk, then approve it fully.
3. Logout, and relogin as the manager for the form.
4. See the form still on the requests page

**Expected behavior:**

The request should be gone once it has been fully approved, and it's status changed to approved.

**Actual Behavior:**

The form is not marked as approved. Rather, it stays on the manager's page as pending.

**Environment:**
 - OS: Windows venv
 - #71 Branch

**Additional context:**

**Logs**

`Internal Server Error: /update-request-status/
Traceback (most recent call last):
  File "C:\Users\spenc\PycharmProjects\003_MAGNA\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spenc\PycharmProjects\003_MAGNA\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spenc\PycharmProjects\003_MAGNA\venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spenc\PycharmProjects\003_MAGNA\forms\views.py", line 157, in update_request_status
    absence_request.save()
  File "C:\Users\spenc\PycharmProjects\003_MAGNA\forms\models.py", line 100, in save
    steps_list = self.workflow.steps
                 ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'steps'
[25/Apr/2024 22:58:09] "POST /update-request-status/ HTTP/1.1" 500 76063
`

**Comment by smblackwll** [comment]
Fixed, but remaining open until the branch is merged in.
