### ISSUE TITLE
Development server not starting after release 1

### ISSUE THREAD

**Issue by smblackwll** [uiowaSEP2024/003_MAGNA#58]
**Describe the bug:**

Upon development server startup, post migration and release, the WSGI application cannot be loaded, and the server does not start.

**To Reproduce:**

1. Go to a console
2. Run the following command:

> python manage.py runserver

Error should appear in console.
Note, if not on windows, the command may be:

> python3 manage.py runserver

**Expected behavior:**

After running the command, the server should start.

**Actual Behavior:**

The command fails, with the following error:
django.core.exceptions.ImproperlyConfigured: WSGI application 'magna.wsgi.application' could not be loaded; Error importing module.

**Screenshots:**

![image](https://github.com/uiowaSEP2024/003_MAGNA/assets/25370145/a5824e82-9a5a-4210-8867-aba3c3abd0d1)

**Environment:**
 - OS: Windows
 - Python Version: 3.9.13, 3.11.8

**Additional context:**

This is after migrations are applied, I'm not sure if the migrations have anything to do with it. 

**Logs**

`Traceback (most recent call last):
  File "C:\003_MAGNA\venv\lib\site-packages\django\core\servers\basehttp.py", line 48, in get_internal_wsgi_application
    return import_string(app_path)
  File "C:\003_MAGNA\venv\lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\003_MAGNA\venv\lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\spenc\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\003_MAGNA\magna\wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "C:\003_MAGNA\venv\lib\site-packages\django\core\wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "C:\003_MAGNA\venv\lib\site-packages\django\core\handlers\wsgi.py", line 118, in __init__
    self.load_middleware()
  File "C:\003_MAGNA\venv\lib\site-packages\django\core\handlers\base.py", line 40, in load_middleware
    middleware = import_string(middleware_path)
  File "C:\003_MAGNA\venv\lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\003_MAGNA\venv\lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\spenc\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'whitenoise'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\spenc\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\spenc\AppData\Local\Programs\Python\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\003_MAGNA\venv\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\003_MAGNA\venv\lib\site-packages\django\core\management\commands\runserver.py", line 139, in inner_run
    handler = self.get_handler(*args, **options)
  File "C:\003_MAGNA\venv\lib\site-packages\django\contrib\staticfiles\management\commands\runserver.py", line 31, in get_handler
    handler = super().get_handler(*args, **options)
  File "C:\003_MAGNA\venv\lib\site-packages\django\core\management\commands\runserver.py", line 78, in get_handler
    return get_internal_wsgi_application()
  File "C:\003_MAGNA\venv\lib\site-packages\django\core\servers\basehttp.py", line 50, in get_internal_wsgi_application
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: WSGI application 'magna.wsgi.application' could not be loaded; Error importing module.
`

**Comment by smblackwll** [comment]
I think this might be due to changing python versions, as now my pycharm console refuses to change python versions.
However, I've tried it with both 3.11.8 and 3.9 so I'm not sure what's causing this outside of that

**Comment by smblackwll** [comment]
Fixed! Turns out when changing python versions, pycharm gets confused and runs the terminal in the wrong python version. 
This is apparently a common issue with windows, so we may need to watch out for it in the future.
